
name: myfind-ci

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update rust
        run: rustup update

      - name: Build the hw1 myfind.
        run: | 
          cd hw1/myfind/
          cargo clean
          cargo build

      - name: Test hw2 buffer
        run: |
          cd hw2/buffer/
          cargo clean
          cargo build
          cargo test

      - name: Test hw2 closure
        run: |
          cd hw2/closure/
          cargo clean
          cargo build
          cargo run

      - name: Test hw2 strcmp
        run: |
          cd hw2/strcmp/
          cargo clean
          cargo build
          cargo test
  
